### ISSUE TITLE
Error using get_article_comments

### ISSUE THREAD

**Issue by lhehnke** [jandix/rzeit2#6]
_get_article_text_ itself works fine, but the respective code in _README.md_ should read 

`tatort_content <- get_article_text(tatort_articles$content$href, timeout = 1)`

Likewise, it should be 

`tatort_comments <- get_article_comments(tatort_articles$content$href[1], timeout = 1)` 

However, using _get_article_comments_ results in the following error message: _Error: '' does not exist in current working directory._

Edit: Not sure whether _get_article_comments_ already does the following (I unsuccessfully searched the function body for it), but getting both the date when each comment was posted and the number of stars/recommendations for each comment would be awesome.

**Comment by jandix** [comment]
Thanks for your suggestions. I updated the README.

I also fixed `Error: '' does not exist in current working directory.`. It seems that `xml2::read_html` does sometimes not parse the additional comments.

I also added the number of stars for each comment. I have to think how I will parse the date since it is only available as **5 minutes ago** or **6 months ago**.
